# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "back-end-1" do |backend1|
    backend1.vm.box = "back-end-1"
    #backend1.vm.box_url = "..."
    backend1.vm.network "private_network", ip: "192.168.1.11", virtualbox__intnet: "network2"
    backend1.vm.network "forwarded_port", guest: 80, host: 9011
  end

  config.vm.define "back-end-2" do |backend2|
    backend2.vm.box = "back-end-2"
    #backend2.vm.box_url = "..."
    backend2.vm.network "private_network", ip: "192.168.1.12", virtualbox__intnet: "network2"
    backend2.vm.network "forwarded_port", guest: 80, host: 9012
  end

  config.vm.define "front-end" do |frontend|
    frontend.vm.box = "front-end"
    #frontend.vm.box_url = "..."
    frontend.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "network2"
    frontend.vm.network "forwarded_port", guest: 80, host: 9010
  end

end
