Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/vivid64"

  config.vm.provision "shell", path: "scripts/provision.sh"

  #config.vm.provider "virtualbox" do |vb|
  #  vb.name = "my_vm"
  #  vb.memory = 1024
  #  vb.cpus = 2
  #  vb.gui = true
  #end

end